"""Generate a weekly pilot summary from the local database.

Usage:
    cd backend
    python scripts/pilot_summary.py [--output pilot_summary_YYYY-MM-DD.md]
"""
import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ai_scanner.app.db.database import Base, SessionLocal, engine
from ai_scanner.app.db.models import AuditLog, Company, ModelRegistry, ReviewRequest, Scan

Base.metadata.create_all(bind=engine)
from ai_scanner.app.schemas import ReviewStatus


def _section(title: str) -> str:
    return f"\n## {title}\n"


def generate_summary(output: Path) -> None:
    db = SessionLocal()
    try:
        now = datetime.now(timezone.utc)
        week_ago = now - timedelta(days=7)

        total_scans = db.query(Scan).count()
        scans_7d = db.query(Scan).filter(Scan.created_at >= week_ago).count()
        accepted = db.query(Scan).filter(Scan.inspector_accepted == True).count()
        overridden = db.query(Scan).filter(Scan.inspector_accepted == False).count()
        completed = accepted + overridden
        agreement_rate = (accepted / completed) if completed else 0.0

        fps = db.query(Scan).filter(
            Scan.inspector_accepted == False,
            Scan.override_condition.in_(["fresh", "near_expiry"]),
            Scan.condition.in_(["expired", "suspicious"]),
        ).count()
        fns = db.query(Scan).filter(
            Scan.inspector_accepted == False,
            Scan.override_condition.in_(["expired", "suspicious"]),
            Scan.condition.in_(["fresh", "near_expiry"]),
        ).count()

        pending_reviews = db.query(ReviewRequest).filter(ReviewRequest.status == ReviewStatus.PENDING).count()
        approved_reviews = db.query(ReviewRequest).filter(ReviewRequest.status == ReviewStatus.APPROVED).count()

        crashes = db.query(AuditLog).filter(
            AuditLog.action == "client_crash", AuditLog.created_at >= week_ago
        ).count()

        active_model = (
            db.query(ModelRegistry)
            .filter(ModelRegistry.status == "active")
            .order_by(ModelRegistry.deployed_at.desc())
            .first()
        )

        companies = db.query(Company).count()

        lines = [
            f"# Pilot Weekly Summary — {now.date().isoformat()}",
            "",
            f"- **Reporting period:** {week_ago.date().isoformat()} to {now.date().isoformat()}",
            f"- **Total scans:** {total_scans}",
            f"- **Scans this week:** {scans_7d}",
            f"- **Companies onboarded:** {companies}",
            "",
            _section("AI Agreement"),
            f"- **Inspector accepted:** {accepted}",
            f"- **Inspector overridden:** {overridden}",
            f"- **AI agreement rate:** {agreement_rate:.2%}" if completed else "- **AI agreement rate:** N/A",
            f"- **False positives (AI over-flagged):** {fps}",
            f"- **False negatives (AI missed spoilage):** {fns}",
            "",
            _section("Review Queue"),
            f"- **Pending reviews:** {pending_reviews}",
            f"- **Approved for retraining:** {approved_reviews}",
            "",
            _section("Operational Health"),
            f"- **Mobile crashes (7d):** {crashes}",
            f"- **Active model:** {active_model.model_id}-{active_model.version}" if active_model else "- **Active model:** none registered",
            f"- **Active model dataset version:** {active_model.dataset_version}" if active_model else "",
            "",
            _section("Actions"),
            "1. Review all overrides with missing reasons.",
            "2. Resolve pending review requests within 48 hours.",
            "3. Investigate any false negatives before the next model retraining.",
            "4. Sync device logs and verify offline upload success rate.",
            "",
            "_Generated by backend/scripts/pilot_summary.py_",
        ]

        output.write_text("\n".join(lines))
        print(f"Summary written to {output}")
    finally:
        db.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path(f"reports/pilot_summary_{datetime.now(timezone.utc).date().isoformat()}.md"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    generate_summary(args.output)


if __name__ == "__main__":
    main()
