apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scanner-ai-ingress
  namespace: scanner-ai
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.smartscanner.example.com
      secretName: scanner-ai-tls
  rules:
    - host: api.smartscanner.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
